# Generated by Django 3.0.4 on 2021-01-25 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_bookings', '0013_auto_20201224_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Awaiting', 'Awaiting'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Denied', 'Denied'), ('Refunded', 'Refunded')], default='Awaiting', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('processor', models.CharField(choices=[('SemSlotProcessor', 'Seminar'), ('IndSlotProcessor', 'Individual')], editable=False, max_length=30)),
                ('processor_data', models.TextField(editable=False)),
                ('purchased_detail', models.TextField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('payment_received', models.DateTimeField(editable=False, null=True)),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='class_bookings.Student')),
            ],
        ),
    ]
