# Generated by Django 3.0.4 on 2021-01-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, unique=True)),
                ('link', models.URLField()),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], max_length=2)),
                ('material_type', models.CharField(choices=[('Videos', 'Videos'), ('Exercises', 'Exercises'), ('Readings', 'Readings')], max_length=20)),
                ('ordering', models.PositiveIntegerField()),
            ],
        ),
    ]
