# Generated by Django 3.1.8 on 2021-08-19 17:18

from django.db import migrations, models
import django.db.models.deletion

from .. import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.TextField()),
                ('feedback_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbacktype')),
            ],
        ),
    ]
