# Generated by Django 3.1.7 on 2021-05-04 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_bookable', models.BooleanField(default=False)),
                ('activity_type', models.CharField(choices=[('IND', 'one-on-one lesson'), ('SEM', 'group seminar')], default='SEM', max_length=3)),
                ('order_shown', models.PositiveSmallIntegerField(default=1)),
                ('is_highlighted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='The lesson date and time')),
                ('duration_in_mins', models.PositiveSmallIntegerField(default=60)),
                ('day_before_reminder_sent', models.BooleanField(default=False, editable=False)),
                ('hour_before_reminder_sent', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarSlot',
            fields=[
                ('baseslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='class_bookings.baseslot')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('video_id', models.CharField(max_length=20)),
                ('seminar', models.ForeignKey(limit_choices_to={'activity_type': 'SEM', 'is_bookable': True}, on_delete=django.db.models.deletion.CASCADE, to='class_bookings.activity')),
                ('students', models.ManyToManyField(blank=True, to='class_bookings.Student')),
            ],
            bases=('class_bookings.baseslot',),
        ),
        migrations.CreateModel(
            name='IndividualSlot',
            fields=[
                ('baseslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='class_bookings.baseslot')),
                ('lesson', models.ForeignKey(blank=True, limit_choices_to={'activity_type': 'IND', 'is_bookable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='class_bookings.activity')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='class_bookings.student')),
            ],
            bases=('class_bookings.baseslot',),
        ),
    ]
