# Generated by Django 2.2.6 on 2019-10-14 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.DateTimeField(verbose_name='The lesson time')),
                ('completed', models.BooleanField(default=False)),
                ('price', models.FloatField(default=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_bookings.Student')),
            ],
        ),
    ]
