# Generated by Django 3.0.4 on 2020-04-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('IND', 'one-on-one lesson'), ('SEM', 'group seminar')], default='IND', max_length=3)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('price', models.FloatField()),
                ('is_bookable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='The lesson date and time')),
                ('duration_in_mins', models.PositiveSmallIntegerField(default=60)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='IndividualSlot',
            fields=[
                ('baseslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='class_bookings.BaseSlot')),
                ('lesson', models.ForeignKey(blank=True, limit_choices_to={'activity_type': 'IND', 'is_bookable': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='class_bookings.Activity')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='class_bookings.Student')),
            ],
            bases=('class_bookings.baseslot',),
        ),
        migrations.CreateModel(
            name='SeminarSlot',
            fields=[
                ('baseslot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='class_bookings.BaseSlot')),
                ('seminar', models.ForeignKey(limit_choices_to={'activity_type': 'SEM', 'is_bookable': True}, on_delete=django.db.models.deletion.PROTECT, to='class_bookings.Activity')),
                ('students', models.ManyToManyField(blank=True, to='class_bookings.Student')),
            ],
            bases=('class_bookings.baseslot',),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
