# Generated by Django 3.0.4 on 2020-11-06 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0004_auto_20200830_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.UUID('da25a29c-7a23-4fb7-9224-3966be6c9a0d'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='seminarslot',
            name='video_id',
            field=models.CharField(default='NO-VIDEO-ID', max_length=20),
            preserve_default=False,
        ),
    ]
