# Generated by Django 3.0.4 on 2020-11-06 01:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0005_auto_20201106_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.UUID('98c730d1-42a0-4225-aef7-5b036ba67ce7'), editable=False, unique=True),
        ),
    ]
