# Generated by Django 3.0.4 on 2020-11-06 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0006_auto_20201106_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.UUID('4dcb807e-d79b-4970-aa4a-cb0e2ca1432e'), editable=False, unique=True),
        ),
    ]
