# Generated by Django 3.0.4 on 2020-11-17 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0007_auto_20201106_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.UUID('e3ef48db-5e51-4ab5-85c6-bc7607ac77ee'), editable=False, unique=True),
        ),
    ]
