# Generated by Django 3.0.4 on 2020-11-21 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0008_auto_20201117_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.UUID('0bd681b9-4951-4f76-87a6-7d1657784e62'), editable=False, unique=True),
        ),
    ]
