# Generated by Django 3.0.4 on 2020-12-05 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0009_auto_20201121_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.UUID('c1879ce5-dfc8-4660-8035-ddc39bc4db68'), editable=False, unique=True),
        ),
    ]
