# Generated by Django 3.0.4 on 2020-12-05 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0010_auto_20201205_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.UUID('8f65c5fc-fdbb-4d49-b2d6-0f8783f727e2'), editable=False, unique=True),
        ),
    ]
