# Generated by Django 3.0.4 on 2020-12-22 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0011_auto_20201205_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseslot',
            name='day_before_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseslot',
            name='hour_before_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.UUID('a85ea07f-4317-440e-b9ca-a6f8c89987d2'), editable=False, unique=True),
        ),
    ]
