# Generated by Django 3.0.4 on 2020-12-24 03:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('class_bookings', '0012_auto_20201222_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='order_shown',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='baseslot',
            name='day_before_reminder_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='baseslot',
            name='hour_before_reminder_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='seminarslot',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='seminarslot',
            name='seminar',
            field=models.ForeignKey(limit_choices_to={'activity_type': 'SEM', 'is_bookable': True}, on_delete=django.db.models.deletion.CASCADE, to='class_bookings.Activity'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
