"""
Django settings for polyglossa project.

Generated by 'django-admin startproject' using Django 3.0
"""
import os

from . import local_settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
FRONTEND_DIR = os.path.join(BASE_DIR, 'frontend')
VUE_DIST_DIR = os.path.join(BASE_DIR, 'frontend', 'dist')


SECRET_KEY = local_settings.SECRET_KEY

DEBUG = local_settings.DEBUG

ALLOWED_HOSTS = local_settings.ALLOWED_HOSTS


# Application definition

PREREQUSITE_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webpack_loader',
    'paypal.standard.ipn',
]

PROJECT_APPS = [
    'class_bookings',
    'payments',
    'learning_materials',
]

INSTALLED_APPS = PREREQUSITE_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_COOKIE_NAME = 'XSRF-TOKEN'


ROOT_URLCONF = 'polyglossa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [TEMPLATES_DIR],   # FAST RELOAD
        'DIRS': [VUE_DIST_DIR], # PRODUCTION
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'polyglossa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(VUE_DIST_DIR, 'css'),
    os.path.join(VUE_DIST_DIR, 'img'),
    os.path.join(VUE_DIST_DIR, 'js'),
    os.path.join(VUE_DIST_DIR),
]

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': DEBUG,
        'BUNDLE_DIR_NAME': '/bundles/',  # must end with slash
        'STATS_FILE': os.path.join(FRONTEND_DIR, 'webpack-stats.json'),
    }
}

# PAYPAL SETTINGS

PAYPAL_TEST = local_settings.PAYPAL_TEST
PAYPAL_EMAIL = local_settings.PAYPAL_EMAIL

PAYPAL_PRIVATE_CERT = '%s/paypal_private.pem' % local_settings.CERT_PATH
PAYPAL_PUBLIC_CERT = '%s/paypal_public.pem' % local_settings.CERT_PATH
PAYPAL_CERT = '%s/paypal_cert.pem' % local_settings.CERT_PATH
PAYPAL_CERT_ID = local_settings.PAYPAL_CERT_ID
