@startuml
title Slot and Type Usage
actor Student
actor Admin


frame "Student Interface" {
    [Sem Form]
    [Ind Form]

    Student --> [Ind Form]: posts
    Student --> [Sem Form]: posts
    
}

frame "Admin Interface" {
    [Admin Forms]

    Admin --> [Admin Forms]: posts
}


frame "Slots" {
    [Sem Slot]
    [Ind Slot]

    [Ind Form] --> [Ind Slot]: fill student and type
    [Sem Form] --> [Sem Slot]: append student
    [Admin Forms] --> [Ind Slot]: creates slot without type
    [Admin Forms] --> [Sem Slot]: creates slot with type
}

frame "Activity" {
    [Sem Activity]
    [Ind Activity]

    [Admin Forms] --> [Sem Activity] : creates
    [Admin Forms] --> [Ind Activity] : creates

    [Ind Slot] ..> [Ind Activity]:  selects
    [Sem Slot] --> [Sem Activity]:  contains
}



@enduml