name: Polyglossa Integration Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Setup Django Database
      run: |
        pipenv run python manage.py makemigrations
        pipenv run python manage.py migrate
    - name: Django Integration Tests
      run: |
        pipenv run python manage.py test
    - name: Linting
      run: |
        pipenv run pylint class_bookings
        pipenv run pylint polyglossa
