name: Polyglossa CI

on: [push]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Configure Files and Env Vars
      shell: bash
      env:
        CERTS_PATH: polyglossa/certs
        PAYPAL_PRIVATE: ${{ secrets.PAYPAL_PRIVATE }}
      run: |
        mkdir -p $HOME/CERTS_PATH
        echo "$PAYPAL_PRIVATE" > $CERTS_PATH/paypal_private_sandbox.pem
        echo "POLYGLOSSA_EMAIL='email@example.com'" >> $GITHUB_ENV
        echo "POLYGLOSSA_EMAIL_PASSWORD='not_real_email_password'" >> $GITHUB_ENV
        echo "POLYGLOSSA_SECRET_KEY=long_secret_key_for_production" >> $GITHUB_ENV
        echo "POLYGLOSSA_DEBUG=True" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=polyglossa.github_ci_settings" >> $GITHUB_ENV
        echo "PAYPAL_EMAIL=paypal_example_email" >> $GITHUB_ENV
        echo "PAYPAL_CERT_ID=not_real_cert_id" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        sudo apt-get install -y swig
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Setup Django Database
      run: |
        pipenv run python manage.py migrate
    - name: Setup Vuetify Frontend
      run: |
        cd frontend/
        npm install
        npm run build
        cd ..
    - name: Testing
      run: |
        pipenv run pytest class_bookings/ payments/ learning_materials/ tasks/
    - name: Linting
      run: |
        pipenv run pylint -d fixme payments polyglossa class_bookings learning_materials tasks */management/commands/*.py
        cd frontend/
        npm run lint
